version: '3.9'

services:
  database:
    image: postgres:14
    container_name: database
    environment:
      TZ: Asia/Bangkok
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - 5432:5432
    networks:
      - networkName

networks:
  networkName:
    driver: bridge
