version: '3.9'

services:
  core-service:
    image: core-service:${VERSION}
    container_name: core-service-prod
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
