version: "3.9"

services:
  database:
    image: postgres:14
    container_name: database
    environment:
      TZ: Asia/Bangkok
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - 5432:5432
